version: '3'
services:
  acquisition_node_donald:
      image: duckietown/cslam-acquisition:x86
      environment:
        - ACQ_ROS_MASTER_URI_DEVICE=donaldthegreat.local
        - ACQ_ROS_MASTER_URI_DEVICE_IP=192.168.43.98
        - ACQ_ROS_MASTER_URI_SERVER=ubuntu-Aleks.local
        - ACQ_ROS_MASTER_URI_SERVER_IP=192.168.43.63
        - ACQ_DEVICE_NAME=donaldthegreat
        - ACQ_BEAUTIFY=1
        - ACQ_STATIONARY_ODOMETRY=0
        - ACQ_ODOMETRY_UPDATE_RATE=15
        - ACQ_POSES_UPDATE_RATE=15
        - ACQ_TEST_STREAM=1
        - ACQ_TOPIC_VELOCITY_TO_POSE=velocity_to_pose_node/pose
        - ACQ_TOPIC_RAW=camera_node/image/compressed
      network_mode: "host"
      restart: always
